remote_theme: just-the-docs/just-the-docs

# Enable or disable the site search
search_enabled: true

# Aux links for the upper right navigation
aux_links:
  "sqlfx on GitHub":
    - "https://github.com/tim-smart/sqlfx"
