remote_theme: just-the-docs/just-the-docs

# Enable or disable the site search
search_enabled: true

# Aux links for the upper right navigation
aux_links:
  "@effect/rpc on GitHub":
    - "https://github.com/effect-ts/rpc"
